version: "3.8"

services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:3000"
    depends_on:
      - mongo-db
    environment:
      MONGO_DB_HOST: mongo-db
      MONGO_DB_PORT: 27017
      MONGO_DB_USER: mongo-user
      MONGO_DB_PASS: 123456
    volumes:
      - .:/app
